# Generated by Django 3.0.4 on 2020-03-22 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transname', models.CharField(max_length=100, verbose_name="Transformer's name")),
                ('transloclat', models.DecimalField(decimal_places=6, max_digits=10, verbose_name="Transformer's Latitude")),
                ('transloclong', models.DecimalField(decimal_places=6, max_digits=10, verbose_name="Transformer's Longitute")),
                ('kvarating', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='KVA Rating')),
                ('phyaddress', models.TextField(verbose_name='Physical Address')),
            ],
            options={
                'verbose_name': 'Transformer',
                'verbose_name_plural': 'Transformers',
            },
        ),
        migrations.CreateModel(
            name='TransformerReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('phasevred', models.DecimalField(decimal_places=3, max_digits=6)),
                ('phasevblue', models.DecimalField(decimal_places=3, max_digits=6)),
                ('phasevyellow', models.DecimalField(decimal_places=3, max_digits=6)),
                ('phasecred', models.DecimalField(decimal_places=3, max_digits=6)),
                ('phasecblue', models.DecimalField(decimal_places=3, max_digits=6)),
                ('phasecyellow', models.DecimalField(decimal_places=3, max_digits=6)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformer', to='transformer.Transformer')),
            ],
        ),
    ]
