# Generated by Django 3.0.4 on 2020-03-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transformerreading',
            options={'verbose_name': 'Transformer Reading', 'verbose_name_plural': 'Transformer Readings'},
        ),
        migrations.AlterField(
            model_name='transformerreading',
            name='phasecblue',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pharse Current Blue'),
        ),
        migrations.AlterField(
            model_name='transformerreading',
            name='phasecred',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pharse Current Red'),
        ),
        migrations.AlterField(
            model_name='transformerreading',
            name='phasecyellow',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pharse Current Yellow'),
        ),
        migrations.AlterField(
            model_name='transformerreading',
            name='phasevblue',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pharse Voltage Blue'),
        ),
        migrations.AlterField(
            model_name='transformerreading',
            name='phasevred',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pharse Voltage Red'),
        ),
        migrations.AlterField(
            model_name='transformerreading',
            name='phasevyellow',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pharse Voltage Yellow'),
        ),
    ]
